name: component
description: "A new Flutter module project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # local
  dependencies:
    path: ../dependencies
  domain:
    path: ../domain
  network:
    path: ../network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: asset/font/Inter/Inter-Black.ttf
          weight: 900
        - asset: asset/font/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: asset/font/Inter/Inter-Bold.ttf
          weight: 700
        - asset: asset/font/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: asset/font/Inter/Inter-Medium.ttf
          weight: 500
        - asset: asset/font/Inter/Inter-Regular.ttf
          weight: 400
        - asset: asset/font/Inter/Inter-Light.ttf
          weight: 300
        - asset: asset/font/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: asset/font/Inter/Inter-Thin.ttf
          weight: 100
