name: guten_book

packages:
  - apps/**
  - shared/**

scripts:
  analyze:
    exec: fvm dart analyze .
  format:
    exec: fvm dart format --set-exit-if-changed .
  get:
    exec: fvm flutter pub get .
  clean:
    exec: fvm flutter clean .
  build:
    exec: fvm dart run build_runner build --delete-conflicting-outputs
  watch:
    run: fvm dart run build_runner watch --delete-conflicting-outputs
