name: guten_book
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  auto_route: ^10.1.0+1
  component:
    path: ../../shared/component
  cupertino_icons: ^1.0.8
  data:
    path: ../../shared/data
  dependencies:
    path: ../../shared/dependencies
  domain:
    path: ../../shared/domain
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1


dev_dependencies:
  auto_route_generator: ^10.2.3
  build_runner:
  flutter_flavorizr: ^2.4.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flavorizr:
  flavors:
    prod:
      app:
        name: "Guten Book"

      android:
        applicationId: "com.guten.book"

      ios:
        bundleId: "com.guten.book"

    staging:
      app:
        name: "Guten Book Staging"

      android:
        applicationId: "com.guten.book.staging"

      ios:
        bundleId: "com.guten.book.staging"

    dev:
      app:
        name: "Guten Book Dev"

      android:
        applicationId: "com.guten.book.dev"

      ios:
        bundleId: "com.guten.book.dev"

flutter:
  uses-material-design: true
