name: dependencies
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  alice_lightweight: ^3.10.0
  auto_size_text_plus: ^3.0.2
  easy_debounce: ^2.0.3
  exprollable_page_view: ^1.0.3
  extended_image: ^10.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  lazy_load_indexed_stack: ^1.2.1
  rxdart: ^0.28.0
  skeletonizer: ^2.0.1
  very_good_infinite_list: ^0.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

