name: domain
description: "A new Flutter module project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  #local
  dependencies:
    path: ../dependencies
  component:
    path: ../component

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
