name: Staging to Firebase App Distribution

on:
  push:
    branches:
      - dev

jobs:
  deploy_android:
    name: Deploy Staging Android to Firebase App Distribution
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          channel: "stable"
      - name: Install melos
        uses: bluefireteam/melos-action@v3
      - name: Clean and Install Flutter dependencies
        run: make clean_get
      - name: Build the APK
        run: flutter build apk --flavor staging --target apps/guten_book/lib/launcher/main_staging.dart --release
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.STAGING_FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: Tester
          file: apps/guten_book/build/app/outputs/flutter-apk/app-staging-release.apk
        
          